# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  #schedule:
  #  - cron: '0 7 * * *'
  workflow_dispatch:

name: bundling

jobs:
  scores:
    runs-on:  ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container: rqthomas/vera-rocker:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        shell: Rscript {0}
        run: |
          remotes::install_deps(".", dep=TRUE, upgrade=TRUE)
          install.packages('bench')
          install.packages('glue')
          install.packages('fs')

      - name: Bundle forecasts
        shell: Rscript {0}
        run: |
          source("submission_processing/bundle-forecasts.R")

      - name: Bundle summaries
        shell: Rscript {0}
        run: |
          source("submission_processing/bundle-summaries.R")
