# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

name: seasonal_forecast_download
jobs:
  seasonal:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container: rqthomas/vera-rocker:latest
    steps:
      - uses: actions/checkout@v3

      - name: Download
        shell: Rscript {0}
        run: |
          install.packages("RCurl")
          source("drivers/seasonal.R")
